CREATE TABLE [dbo].[CodeMast] (
    [Recnum]      BIGINT       IDENTITY (1, 1) NOT NULL,
    [TYPE]        VARCHAR (10) DEFAULT (' ') NOT NULL,
    [CODE]        VARCHAR (10) DEFAULT (' ') NOT NULL,
    [DESCRIPTION] VARCHAR (30) DEFAULT (' ') NOT NULL,
    CONSTRAINT [CodeMast_INDEX01] PRIMARY KEY CLUSTERED ([TYPE] ASC, [CODE] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_CodeMast_TYPE] FOREIGN KEY ([TYPE]) REFERENCES [dbo].[CodeType] ([TYPE])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CodeMast_INDEX00]
    ON [dbo].[CodeMast]([Recnum] ASC) WITH (FILLFACTOR = 70);

